// Autogenerated from Pigeon (v0.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, FLTType) {
  FLTTypeTYPE_A = 0,
  FLTTypeTYPE_B = 1,
};

@class FLTVersion;
@class FLTGoods;

@interface FLTVersion : NSObject
@property(nonatomic, copy, nullable) NSString * string;
@end

@interface FLTGoods : NSObject
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSNumber * price;
@property(nonatomic, strong, nullable) NSNumber * expiryDate;
@property(nonatomic, assign) FLTType type;
@end

@protocol FLTExampleApi
-(nullable FLTVersion *)getPlatformVersion:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTExampleApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTExampleApi> _Nullable api);

@protocol FLTStoreApi
-(void)sell:(FLTGoods*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTStoreApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTStoreApi> _Nullable api);

NS_ASSUME_NONNULL_END
